# Generated by Django 5.2 on 2025-06-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_shopgram_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopgram",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
