# Generated by Django 5.2 on 2025-06-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staticpage",
            name="category",
        ),
        migrations.DeleteModel(
            name="StaticPageCategory",
        ),
    ]
