# Generated by Django 5.2 on 2025-06-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_staticpage_category_delete_staticpagecategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staticpage",
            options={"ordering": ["order", "title"]},
        ),
        migrations.AddField(
            model_name="staticpage",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first in menus"
            ),
        ),
    ]
