# Generated by Django 5.2 on 2025-06-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField(blank=True)),
                (
                    "banner_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Page",
            },
        ),
    ]
