# Generated by Django 5.2 on 2025-06-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_aboutpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="section_image1",
            field=models.ImageField(blank=True, null=True, upload_to="about/"),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="section_image2",
            field=models.ImageField(blank=True, null=True, upload_to="about/"),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="section_image3",
            field=models.ImageField(blank=True, null=True, upload_to="about/"),
        ),
    ]
