# Generated by Django 5.2 on 2025-06-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_aboutpage_section_image4"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Visit Our Store", max_length=255)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "open_time",
                    models.TextField(help_text="e.g., Every day 11am to 7pm"),
                ),
                (
                    "map_embed_url",
                    models.TextField(
                        help_text="Paste the Google Maps iframe `src` URL here"
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("tiktok_url", models.URLField(blank=True, null=True)),
                ("pinterest_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Contact Page",
                "verbose_name_plural": "Contact Pages",
            },
        ),
    ]
