# Generated by Django 5.2 on 2025-06-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_contactpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "location_type",
                    models.CharField(
                        choices=[("in_store", "In-Store"), ("overseas", "Overseas")],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("referral_source", models.CharField(max_length=255)),
                ("existing_customer", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preferred_locations",
                    models.ManyToManyField(
                        related_name="appointments", to="content.location"
                    ),
                ),
            ],
        ),
    ]
