# Generated by Django 5.2 on 2025-06-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_location_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="preferred_locations",
        ),
        migrations.AddField(
            model_name="appointment",
            name="preferred_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="content.location",
            ),
        ),
    ]
