# Generated by Django 5.2 on 2025-06-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_remove_appointment_preferred_locations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="preferred_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
