# Generated by Django 5.2 on 2025-06-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_appointment_preferred_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="preferred_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
